kind: pipeline
name: t2-kernel-compiletest

clone:
  depth: 1

steps:
- name: compile
  image: archlinux
  pull: always
  commands:
    - curl --output /tmp/pacman-static https://pkgbuild.com/~morganamilo/pacman-static/x86_64/bin/pacman-static # Workaround https://bugs.archlinux.org/task/69563
    - chmod +x /tmp/pacman-static
    - /tmp/pacman-static --noconfirm -Syy
    - curl --output /tmp/glibc-linux4-2.35-2-x86_64.pkg.tar.zst  https://dl.t2linux.org/ci/glibc-linux4-2.35-2-x86_64.pkg.tar.zst 
    - curl --output /tmp/lib32-glibc-linux4-2.35-2-x86_64.pkg.tar.zst https://dl.t2linux.org/ci/lib32-glibc-linux4-2.35-2-x86_64.pkg.tar.zst
    - printf 'y\ny\n' | /tmp/pacman-static -U /tmp/glibc-linux4-2.35-2-x86_64.pkg.tar.zst /tmp/lib32-glibc-linux4-2.35-2-x86_64.pkg.tar.zst
    - pacman --noconfirm -Syu
    - pacman --noconfirm --needed -S base-devel sudo bc kmod libelf pahole cpio perl tar xz git
    - useradd builduser -m
    - passwd -d builduser
    - printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # passwordless sudo
    - chown -R builduser:builduser ./
    - sudo -u builduser bash -c 'make defconfig'
    - sudo -u builduser bash -c 'echo -e "CONFIG_BRCMUTIL=y\nCONFIG_BRCMFMAC=y\nCONFIG_BRCMFMAC_PCIE=y\nCONFIG_BRCMDBG=y\n" >> .config'
    - sudo -u builduser bash -c 'echo -e "CONFIG_DRM_AMDGPU=y\n" >> .config'
    - sudo -u builduser bash -c 'echo -e "CONFIG_SENSORS_APPLESMC=y\n" >> .config'
    - sudo -u builduser bash -c 'echo -e "CONFIG_MOUSE_BCM5974=y\n" >> .config'
    - sudo -u builduser bash -c 'echo -e "CONFIG_MEDIA_SUPPORT=y\nCONFIG_MEDIA_USB_SUPPORT=y\nCONFIG_MEDIA_CAMERA_SUPPORT=y\nCONFIG_USB_VIDEO_CLASS=y\n" >> .config'
    - sudo -u builduser bash -c 'yes "" | make oldconfig'
    - sudo -u builduser bash -c 'make -j16'
